### ISSUE TITLE
Cannot find module `.../parser/errors` when running CLI

### ISSUE THREAD

**Issue by spenserblack** [spenserblack/steamdown#262]
Bisected to cd05934bdd6ce4fba1b054c6ca797a13e87df83a
